### ISSUE TITLE
Slides do meetup 5 trocados

### ISSUE THREAD

**Issue by tyronedamasceno** [GruPy-RN/Meetup#1]
Os slides das palestras [De front-end a full-stack](https://github.com/GruPy-RN/Meetup/blob/master/Meetup-5/Slides/de-front-end-a-full-stack-aprendendo-python-e-django/de-front-end-a-full-stack-aprendendo-python-e-django.pdf) e [Como desprogramei minha carreira](https://github.com/GruPy-RN/Meetup/blob/master/Meetup-5/Slides/como-desprogamei-minha-carreira/como-desprogamei-minha-carreira.pdf) estão trocados.

**Comment by allythy** [comment]
Corrigido, obrigado.
